export interface IFormF5 {
  steps: {
    step1: boolean,
    step2: boolean,
    step3: boolean,
  },
  tipo_de_operacion: {
    tipo: 'Inicial' | 'Corrección' | 'Cambio de formulario' | '',
    ingreso_o_egreso: 'Ingreso' | 'Egreso' | '',
  },
  identificacion_de_la_declaracion: {
    fecha_tramite: string,
    nit_imc: string,
    dv: string,
    numero_declaracion: string | number
  },
  identificacion_operacion_anterior: {
    fecha_operacion: string,
    nit_imc: string,
    dv: string,
    numero_deuda_externa: string | number,
    numero_declaracion_cambio: string | number
  },
  declaracion_detalle: {
    devolucion: boolean,
    informacion_consolidada: boolean,
  },
  tipo_identidad: {
    otros: string,
    tipo: string
  },
  identificacion_de_la_empresa: {
    tipo_identificacion: string,
    numero_identifiacion: string | number,
    dv: string,
    nombre: string,
    telefono: string,
    direccion: string,
    ciudad: string
  },
  descripcion_de_la_operacion: {
    cod_mda_negociacion: string,
    vr_total_mda_negociacion: string,
    tasa_de_cambio_dolar: string,
    valor_total_dolares: number,
  },
  informacion_de_la_operacion: [{
    numero_cambiario: string,
    valor_total_dolares: string,
  }],
  observaciones: string
  valor_total_operaciones?: number
}

export const numeralesCambiariosF5Ingreso = [{ codigo: '1070', texto: 'Venta de petróleo crudo y gas natural de producción nacional' },
{ codigo: '1510', texto: 'Gastos de exportación de bienes no incluidos en la declaración de exportación definitiva' },
{ codigo: '1520', texto: 'Servicios portuarios y de aeropuerto' },
{ codigo: '1530', texto: 'Turismo' },
{ codigo: '1535', texto: 'Servicio de transporte por tubería de petróleo crudo y gas natural' },
{ codigo: '1536', texto: 'Contratos de Asociación Ingresos' },
{ codigo: '1540', texto: 'Servicios financieros' },
{ codigo: '1600', texto: 'Compra a residentes que compran y venden divisas de manera profesional' },
{ codigo: '1601', texto: 'Otros conceptos' },
{ codigo: '1602', texto: 'Pago de exportación de servicios con divisas a través de proveedores de servicios de pago agregadores' },
{ codigo: '1631', texto: 'Intereses por la emisión y colocación de bonos en moneda legal colombiana' },
{ codigo: '1695', texto: 'Servicios culturales, artísticos y deportivos' },
{ codigo: '1696', texto: 'Pasajes' },
{ codigo: '1703', texto: 'Servicios de comunicaciones' },
{ codigo: '1704', texto: 'Comisiones no financieras' },
{ codigo: '1706', texto: 'Viajes de negocios, gastos educativos, pagos laborales a residentes, seguridad social' },
{ codigo: '1707', texto: 'Servicios diplomáticos, consulares y organismos internacionales' },
{ codigo: '1708', texto: 'Comercialización de mercancías de usuarios de zona franca' },
{ codigo: '1710', texto: 'Servicios médicos, quirúrgicos y hospitalarios' },
{ codigo: '1711', texto: 'Suscripciones, cuotas de afiliación y aportes periódicos' },
{ codigo: '1712', texto: 'Venta de mercancías no consideradas exportación' },
{ codigo: '1713', texto: 'Arrendamiento operativo' },
{ codigo: '1714', texto: 'Servicios de publicidad' },
{ codigo: '1809', texto: 'Remesas de trabajadores' },
{ codigo: '1810', texto: 'Donaciones y transferencias que no generan contraprestación' },
{ codigo: '1811', texto: 'Redención por la emisión y colocación de bonos en moneda legal colombiana' },
{ codigo: '1812', texto: 'Remesas de trabajadores para la adquisición de vivienda' },
{ codigo: '1813', texto: 'Remesas de personas naturales colombianas no residentes con destino a cuentas de ahorro de trámite simplificado' },
{ codigo: '1815', texto: 'Marcas, patentes, regalías y compensaciones' },
{ codigo: '1840', texto: 'Servicios empresariales, profesionales y técnicos' },
{ codigo: '1980', texto: 'Seguros y reaseguros' },
{ codigo: '1990', texto: 'Remesas pagadas en moneda legal colombiana a través de concesionarios de servicios de correos' },
{ codigo: '1991', texto: 'Ingreso de divisas en cuentas de compensación por servicios financieros de correos' },
{ codigo: '5366', texto: 'Compra de saldos de cuentas de compensación de Ecopetrol' },
{ codigo: '5370', texto: 'Compra de saldos de cuentas de compensación de la DTN' },
{ codigo: '5375', texto: 'Operaciones de derivados o por el pago de margen o prima' },
{ codigo: '5377', texto: 'Transferencias presupuestales entre cuentas de compensación de la DTN y entidades del sector público - Ingreso' },
{ codigo: '5378', texto: 'Traslados entre cuentas de compensación de un mismo titular. Ingresos' },
{ codigo: '5379', texto: 'Compra de saldos de cuentas de compensación del - sector privado' },
{ codigo: '5381', texto: 'Compra de saldos de cuentas en moneda extranjera en intermediarios del mercado cambiario sector privado' },
{ codigo: '5382', texto: 'Compra de saldos de cuentas en el exterior Sector Privado' },
{ codigo: '5383', texto: 'Compra de saldos de cuentas en moneda extranjera en intermediarios del mercado cambiario -sector público' },
{ codigo: '5384', texto: 'Compra de saldos de cuentas en el exterior Sector Público' },
{ codigo: '5385', texto: 'Errores Bancarios de cuenta de compensación' },
{ codigo: '5386', texto: 'Traslado de recursos líquidos entre administradores de activos en el exterior ingreso' },
{ codigo: '5387', texto: 'Ingresos por traslados desde la cuenta del mercado no regulado del mismo titular' },
{ codigo: '5390', texto: 'Compra de saldos de cuentas de compensación del resto del sector público' },
{ codigo: '5395', texto: 'Compra de saldos de cuentas de compensación de la Federación Nacional de Cafeteros' },
{ codigo: '5405', texto: 'Operaciones overnight' },
{ codigo: '5450', texto: 'Ingreso de divisas por liquidación de contratos de derivados peso-divisa o divisa-divisa a través de cuenta de compensación, celebrados entre la D.T.N. e IMC o agentes del exterior autorizados' },
{ codigo: '5451', texto: 'Ingreso de divisas por liquidación en cuentas de compensación de contratos de derivados peso-divisa o divisadivisa a través de cuentas de compensación, celebrados entre Ecopetrol e IMC o agentes del exterior autorizados' },
{ codigo: '5452', texto: 'Ingreso de divisas por liquidación de contratos de derivados peso-divisa o divisa-divisa a través de cuentas de compensación, celebrados entre la Federación Nacional de Cafeteros e Intermediarios del Mercado Cambiario agentes del exterior autorizados' },
{ codigo: '5453', texto: 'Ingreso de divisas por liquidación de contratos de derivados peso-divisa o divisa-divisa a través de cuentas de compensación, celebrados entre entidades del sector privado e Intermediarios del Mercado Cambiario o agentes del exterior autorizados' },
{ codigo: '5454', texto: 'Ingreso de divisas por liquidación de contratos de derivados peso-divisa o divisa-divisa a través de cuentas de compensación, celebrados entre el resto del sector público e Intermediarios del Mercado Cambiario o agentes del exterior autorizados' },
{ codigo: '5455', texto: 'Compra de divisas a agentes del exterior proveedores de cobertura por liquidación de contratos de derivados' },
{ codigo: '5457', texto: 'Compra de divisas para acreditar cuentas de no residentes de uso exclusivo para operaciones de crédito externo en moneda legal' },
{ codigo: '5458', texto: 'Venta en moneda extranjera a no residentes de cartera o instrumentos de pago de operaciones internas' },
{ codigo: '5460', texto: 'Venta en moneda extranjera a IMC de cartera o instrumentos de pago de operaciones internas' },
{ codigo: '5499', texto: 'Compra de dólares por los IMC provenientes de la redención del depósito en dólares de que trata el artículo 47 de la R.E. 1/18 J.D. Ingreso' },
{ codigo: '5464', texto: 'Compra de divisas para acreditar cuentas de no residentes de uso exclusivo para pagos de exportaciones de servicios' },
]
export const numeralesCambiariosF5Egreso = [
  { codigo: '2016', texto: 'Gastos de importación y/o exportación de bienes no incluidos en la factura de los proveedores de los bienes y/o contrato de compraventa de bienes o en la declaración de exportación' },
  { codigo: '2018', texto: 'Compra de petróleo crudo y gas natural de producción nacional' },
  { codigo: '2030', texto: 'Servicios portuarios y de aeropuerto' },
  { codigo: '2040', texto: 'Turismo' },
  { codigo: '2126', texto: 'Intereses por financiación de importaciones deuda privada otorgadas por IMC' },
  { codigo: '2136', texto: 'Intereses por financiación de importaciones deuda privada otorgadas por proveedores u otros no residentes' },
  { codigo: '2137', texto: 'Intereses por financiación de importaciones deuda pública' },
  { codigo: '2215', texto: 'Intereses deuda de la banca comercial' },
  { codigo: '2270', texto: 'Servicios financieros' },
  { codigo: '2621', texto: 'Contratos de Asociación Egreso' },
  { codigo: '2800', texto: 'Servicios de comunicaciones' },
  { codigo: '2850', texto: 'Comisiones no financieras' },
  { codigo: '2895', texto: 'Servicios culturales, artísticos y deportivos' },
  { codigo: '2896', texto: 'Pasajes' },
  { codigo: '2900', texto: 'Viajes de negocios, gastos educativos, pagos laborales a no residentes, seguridad social' },
  { codigo: '2903', texto: 'Marcas, patentes, regalías y compensaciones' },
  { codigo: '2904', texto: 'Otros conceptos' },
  { codigo: '2905', texto: 'Venta a residentes que compran y venden divisas de manera profesional' },
  { codigo: '2906', texto: 'Servicios empresariales, profesionales y técnicos' },
  { codigo: '2907', texto: 'Servicios diplomáticos y consulares y de organismos internacionales' },
  { codigo: '2908', texto: 'Comercialización de mercancías de usuarios de zona franca' },
  { codigo: '2909', texto: 'Servicio de transporte por tubería de petróleo crudo y gas natural' },
  { codigo: '2910', texto: 'Donaciones, transferencias y remesas de trabajadores no residentes que no generan contraprestación' },
  { codigo: '2911', texto: 'Emisión y colocación de bonos en moneda legal colombiana' },
  { codigo: '2912', texto: 'Valores extranjeros emitidos en el exterior e inscritos en el RNVE' },
  { codigo: '2913', texto: 'Servicios médicos quirúrgicos y hospitalarios' },
  { codigo: '2914', texto: 'Suscripciones, cuotas de afiliación y aportes periódicos' },
  { codigo: '2915', texto: 'Compra de mercancías no consideradas importación' },
  { codigo: '2916', texto: 'Arrendamiento operativo' },
  { codigo: '2917', texto: 'Servicios de publicidad' },
  { codigo: '2918', texto: 'Valores emitidos por entidades extranjeras e inscritos en el RNVE' },
  { codigo: '2919', texto: 'Pago de importación de servicios con divisas a través de proveedores de servicios de pago agregadores' },
  { codigo: '2950', texto: 'Seguros y reaseguros' },
  { codigo: '2990', texto: 'Remesas entregadas en moneda legal colombiana a través de concesionarios de servicios de correos' },
  { codigo: '2991', texto: 'Egreso de divisas en cuentas de compensación por servicios financieros de correos' },
  { codigo: '2992', texto: 'Reembolso de remesas desde cuentas de ahorro de trámite simplificado de personas naturales colombianas no residentes' },
  { codigo: '4650', texto: 'Pago de afiliación y cuotas a organismos internacionales' },
  { codigo: '5896', texto: 'Venta de divisas para consignar en cuentas de compensación de Ecopetrol' },
  { codigo: '5897', texto: 'Venta de divisas para consignar en cuentas de compensación de la Federación Nacional de Cafeteros' },
  { codigo: '5900', texto: 'Venta de divisas para consignar en cuentas de compensación de la Dirección del Tesoro Nacional DTN' },
  { codigo: '5908', texto: 'Venta de divisas para consignar en cuentas de compensación del sector privado.' },
  { codigo: '5910', texto: 'Operaciones de derivados o por el pago de margen o prima.' },
  { codigo: '5911', texto: 'Transferencias presupuestales entre cuentas de compensación de la DTN y entidades del sector público -Egreso.' },
  { codigo: '5912', texto: 'Traslados entre cuentas de compensación de un mismo titular. Egresos' },
  { codigo: '5913', texto: 'Depósitos en cuentas en el exterior - sector privado.' },
  { codigo: '5914', texto: 'Traslado de recursos líquidos entre administradores de activos en el exterior egreso' },
  { codigo: '5915', texto: 'Errores bancarios de cuenta de compensación' },
  { codigo: '5916', texto: 'Depósitos en cuentas en el exterior - sector público.' },
  { codigo: '5917', texto: 'Egresos por traslados a la cuenta del mercado no regulado del mismo titular' },
  { codigo: '5920', texto: 'Venta de divisas para consignar en cuentas de compensación del resto del sector público.' },
  { codigo: '5930', texto: 'Operaciones overnight.' },
  { codigo: '5800', texto: 'Egreso de divisas por liquidación de contratos de derivados peso-divisa o divisa-divisa a través de cuentas de compensación, celebrados entre la D.T.N. e Intermediarios del Mercado Cambiario o agentes del exterior autorizados.' },
  { codigo: '5801', texto: 'Egreso de divisas por liquidación de contratos de derivados peso-divisa o divisa-divisa con cumplimiento efectivo (DF) a través de cuentas de compensación, celebrados entre Ecopetrol e Intermediarios del Mercado Cambiario o agentes del exterior autorizados' },
  { codigo: '5802', texto: 'Egreso de divisas por liquidación de contratos de derivados peso-divisa o divisa-divisa con cumplimiento efectivo (DF) a través de cuentas de compensación, celebrados entre la Federación Nacional de Cafeteros e Intermediarios del Mercado Cambiario o agentes del exterior autorizados.' },
  { codigo: '5803', texto: 'Egreso de divisas por liquidación de contratos de derivados peso-divisa o divisa-divisa con cumplimiento efectivo (DF) a través de cuentas de compensación, celebrados entre entidades del sector privado e Intermediarios del Mercado Cambiario o agentes del exterior autorizados.' },
  { codigo: '5804', texto: 'Egreso de divisas por liquidación de contratos de derivados peso-divisa o divisa-divisa con cumplimiento efectivo (DF) a través de cuentas de compensación, celebrados entre el resto del sector público e Intermediarios del Mercado Cambiario o agentes del exterior autorizados.' },
  { codigo: '5805', texto: 'Venta de divisas a agentes del exterior proveedores de cobertura por liquidación de contratos de derivados.' },
  { codigo: '5806', texto: 'Venta de divisas para debitar cuentas de uso exclusivo para operaciones de crédito externo en pesos de no residentes.' },
  { codigo: '5807', texto: 'Pago en moneda extranjera a no residentes de cartera o instrumentos de pago de operaciones internas' },
  { codigo: '5808', texto: 'Pago en moneda extranjera a IMC de cartera o instrumentos de pago de operaciones internas' },
  { codigo: '5809', texto: 'Venta de divisas por débitos en las cuentas de no residentes de uso exclusivo para pagos de exportaciones de servicios' },
]
